#!/usr/bin/env node
const fs = require("fs");

if (process.argv.length !== 3) {
	console.error("Usage: pretty-json filename");
	process.exit(1);
}

fs.readFile(process.argv[2], "utf8", function (err, ugly) {
	if (err) {
		console.error(err);
		process.exit(1);
	}

	const pretty = JSON.stringify(JSON.parse(ugly), null, 2);
	fs.writeFile(process.argv[2], pretty, function(err2) {
		if (err2) {
			console.error(err);
			process.exit(1);
		}
	});
});
